[package]
name = "BeYewTify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.133"
serde_json = "1.0.74"
serde_derive = "1.0.133"
lazy_static = "1.4.0"
yew = "0.19.3"